SETUP:
 value: 'Yes'
 options: ['Yes', 'No']
 description: 'Show Setup dialog?'

BUZZER_GPIO:
 value: 16
 description: 'Buzzer GPIO'

BREWNAME:
 value:
 description: 'Brew Name'

UNIT:
 value: C
 options: ['C','F']
 description: 'Temperature Unit'

THERMOMETER_TYPE:
 value: 1WIRE
 options: ['1WIRE','USB','DUMMY', '1WIRE_V2']
 description: 'Thermometer Type !!!RESTART AFTER CHANGE OF THIS PARAMETER!!!'

SWITCH_TYPE:
 value: GPIO
 options: ['GPIO','CHIP-GPIO','GPIOSYS','PIFACE','GEMBIRD','WIFISOCKET','DUMMY']
 description: 'Actor Type !!!RESTART AFTER CHANGE OF THIS PARAMETER!!!'

SEND_STATS:
 value: 'True'
 options: ['True', 'False']
 description: 'Sending statistic informaiton to CraftBeerPI. This helps to improve CraftBeerPI in the future'

USE_LCD:
 value: 'False'
 options: ['True', 'False']
 description: 'Use LCD'


BREWERY_NAME:
 value:
 description: 'Name of your brewery'

USERNAME:
 value: admin

PASSWORD:
 value: 123

DUMMY_TEMP_SIMULATOR:
 value: 'No'
 options: ['Yes', 'No']

WRITE_TEMP_FILE:
 value: 'YES'
 options: ['Yes', 'No']

THEME:
 value: static/themes/dark-theme.css
 options: ['static/themes/metal-theme.css', 'static/themes/metal2-theme.css', 'static/themes/wood-theme.css', 'static/themes/dark-theme.css', 'static/themes/blue-theme.css', 'static/themes/paper-theme.css','']
 description: 'Color theme'

WIFI_SOCKET_IP:
  value:
  description: 'Comma separated liste of wifi socket IP addresses'

WIFI_SOCKET_USER:
  value: admin
  description: 'username for wifi socket'

WIFI_SOCKET_PASSWORD:
  value: 12345
  description: 'password for wifi socket'
